Repository nanglang-18jo/nanglang-eats, pull requests merged in 2024-11, with the labels that each got.

#3 [feat] 프로젝트 설정 추가
  src/main/java/com/sparta/nanglangeats/global/common/dto/CommonResponse.java
  src/main/java/com/sparta/nanglangeats/global/common/entity/Timestamped.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/CustomException.java
  src/main/java/com/sparta/nanglangeats/global/config/AuditingConfig.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat

#22 [feat] 커스텀 인증 구현
  src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
  src/main/java/com/sparta/nanglangeats/global/config/security/entrypoint/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/nanglangeats/global/config/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/sparta/nanglangeats/global/config/security/provider/CustomAuthenticationProvider.java
  src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
Labels: feat

#29 [etc] README 수정
  README.md
Labels: documentation

#36 [fix] ControllerUtil 매개변수 수정
  src/main/java/com/sparta/nanglangeats/global/common/util/ControllerUtil.java
Labels: fix

#39 [fix] 유저 회원 가입 기능 수정
  src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java
  src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserSignupRequest.java
  src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/dto/request/UserSignupServiceRequest.java
  src/main/java/com/sparta/nanglangeats/global/common/annotation/Email.java
  src/main/java/com/sparta/nanglangeats/global/common/annotation/Password.java
  src/main/java/com/sparta/nanglangeats/global/common/annotation/Username.java
  src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/EmailValidator.java
  src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/PasswordValidator.java
  src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/UsernameValidator.java
  src/main/java/com/sparta/nanglangeats/global/common/entity/Timestamped.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/nanglangeats/global/config/AuditingConfig.java
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
  src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserSignupRequestTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
Labels: fix

#40 [feat] 상품 등록 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/image/enums/ImageCategory.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/ProductController.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/dto/request/ProductCreateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/dto/response/ProductCreateResponse.java
  src/main/java/com/sparta/nanglangeats/domain/product/entity/Product.java
  src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java
  src/main/java/com/sparta/nanglangeats/domain/store/entity/Store.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
Labels: feat

#42 [fix] 유저 회원 가입 메서드명 수정
  src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
  src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
Labels: fix

#47 [feat] Spring Security MethodSecurity 설정 추가
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
Labels: feat

#50 [feat] 가게 정보 수정 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/image/repository/ImageRepository.java
  src/main/java/com/sparta/nanglangeats/domain/image/service/dto/ImageService.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/StoreController.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/request/StoreRequest.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/response/StoreResponse.java
  src/main/java/com/sparta/nanglangeats/domain/store/entity/Store.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
Labels: feat

#59 [feat] 유저 정보 수정 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java
  src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserUpdateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
  src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
Labels: feat

#61 [feat] 유저 회원 탈퇴 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java
  src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
Labels: feat

#65 [feat] 주문 등록 기능 구현
  .gitignore
  src/main/java/com/sparta/nanglangeats/domain/order/controller/OrderController.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/request/OrderCreateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/response/OrderCreateResponse.java
  src/main/java/com/sparta/nanglangeats/domain/order/entity/Order.java
  src/main/java/com/sparta/nanglangeats/domain/order/entity/OrderProduct.java
  src/main/java/com/sparta/nanglangeats/domain/order/repository/OrderProductRepository.java
  src/main/java/com/sparta/nanglangeats/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/nanglangeats/domain/order/service/OrderService.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
Labels: feat

#66 [feat] 상품 수정 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/product/controller/ProductController.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/dto/request/ProductRequest.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/dto/response/ProductCreateResponse.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/dto/response/ProductResponse.java
  src/main/java/com/sparta/nanglangeats/domain/product/entity/Product.java
  src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/response/StoreResponse.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
Labels: feat

#68 [feat] 상품 삭제 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/image/entity/Image.java
  src/main/java/com/sparta/nanglangeats/domain/image/service/ImageService.java
  src/main/java/com/sparta/nanglangeats/domain/product/controller/ProductController.java
  src/main/java/com/sparta/nanglangeats/domain/product/entity/Product.java
  src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
Labels: feat

#74 [fix] 가게 엔티티 변경 / 상품 서비스 버그 수정
  src/main/java/com/sparta/nanglangeats/domain/image/service/ImageService.java
  src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/request/StoreRequest.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/response/StoreDetailResponse.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/response/StoreListResponse.java
  src/main/java/com/sparta/nanglangeats/domain/store/entity/Store.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
Labels: fix

#79 [fix] - 유저 엔드포인트 URL 수정
  src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
  src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
Labels: fix

#80 [feat] 유저 정보 조회 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java
  src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/MyInfoResponse.java
  src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/UserDetailResponse.java
  src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
  src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
Labels: feat

#90 [feat] 배송 주소 수정 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/delivery_address/controller/DeliveryAddressController.java
  src/main/java/com/sparta/nanglangeats/domain/delivery_address/controller/dto/request/DeliveryAddressUpdateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/delivery_address/entity/DeliveryAddress.java
  src/main/java/com/sparta/nanglangeats/domain/delivery_address/service/DeliveryAddressService.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
Labels: feat

#91 [feat] 배송 주소 삭제 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/delivery_address/controller/DeliveryAddressController.java
  src/main/java/com/sparta/nanglangeats/domain/delivery_address/service/DeliveryAddressService.java
Labels: feat

#95 [feat] 가게/상품 검색 기능 구현
  build.gradle
  src/main/java/com/sparta/nanglangeats/domain/product/controller/ProductController.java
  src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepository.java
  src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/StoreController.java
  src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/response/StoreListResponse.java
  src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepository.java
  src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepositoryCustomImpl.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
  src/main/java/com/sparta/nanglangeats/global/config/QuerydslConfig.java
Labels: feat

#94 [feat] Swagger 환경 설정
  build.gradle
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
  src/main/java/com/sparta/nanglangeats/global/config/SwaggerConfig.java
Labels: feat

#97 [fix] Refresh Token 디렉토리 구조 수정
  src/main/java/com/sparta/nanglangeats/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/nanglangeats/domain/auth/entity/RefreshToken.java
  src/main/java/com/sparta/nanglangeats/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/nanglangeats/domain/auth/service/RefreshTokenService.java
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
  src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java
Labels: fix

#105 [feat] DeliveryAddress 조회
  src/main/java/com/sparta/nanglangeats/domain/user/controller/DeliveryAddressController.java
  src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/DeliveryAddressDetailResponse.java
  src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/DeliveryAddressListResponse.java
  src/main/java/com/sparta/nanglangeats/domain/user/repository/DeliveryAddressRepository.java
  src/main/java/com/sparta/nanglangeats/domain/user/service/DeliveryAddressService.java
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
Labels: feat

#106 [feat] 리뷰 수정 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java
  src/main/java/com/sparta/nanglangeats/domain/review/entity/Review.java
  src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java
  src/main/java/com/sparta/nanglangeats/domain/store/entity/Store.java
  src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
Labels: feat

#110 [feat] 가게별 리뷰 목록 조회 기능
  src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java
  src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/response/ReviewListResponse.java
  src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java
Labels: feat

#115 [feat] 내 리뷰 조회
  src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java
  src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/response/MyReviewListResponse.java
  src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java
Labels: feat

#113 [ feat] 주문 조회 기능 구현
  src/main/java/com/sparta/nanglangeats/domain/order/controller/OrderController.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/request/OrderCreateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/request/OrderUpdateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/response/OrderDetailResponse.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/response/OrderProductResponse.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/response/OrderSummaryResponse.java
  src/main/java/com/sparta/nanglangeats/domain/order/entity/Order.java
  src/main/java/com/sparta/nanglangeats/domain/order/entity/OrderProduct.java
  src/main/java/com/sparta/nanglangeats/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/nanglangeats/domain/order/service/OrderService.java
  src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepository.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
Labels: feat

#116 [feat] 결제 CRUD 구현
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/response/OrderDetailResponse.java
  src/main/java/com/sparta/nanglangeats/domain/order/controller/dto/response/OrderSummaryResponse.java
  src/main/java/com/sparta/nanglangeats/domain/order/entity/Order.java
  src/main/java/com/sparta/nanglangeats/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/nanglangeats/domain/payment/client/TossPayment.java
  src/main/java/com/sparta/nanglangeats/domain/payment/client/TossPaymentClient.java
  src/main/java/com/sparta/nanglangeats/domain/payment/client/TossPaymentSimulator.java
  src/main/java/com/sparta/nanglangeats/domain/payment/controller/PaymentController.java
  src/main/java/com/sparta/nanglangeats/domain/payment/controller/request/PaymentApproveRequest.java
  src/main/java/com/sparta/nanglangeats/domain/payment/controller/request/PaymentUpdateRequest.java
  src/main/java/com/sparta/nanglangeats/domain/payment/controller/response/PaymentResponse.java
  src/main/java/com/sparta/nanglangeats/domain/payment/entity/Payment.java
  src/main/java/com/sparta/nanglangeats/domain/payment/enums/PaymentStatus.java
  src/main/java/com/sparta/nanglangeats/domain/payment/enums/PaymentType.java
  src/main/java/com/sparta/nanglangeats/domain/payment/repository/PaymentRepository.java
  src/main/java/com/sparta/nanglangeats/domain/payment/service/PaymentService.java
  src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
  src/main/java/com/sparta/nanglangeats/global/config/RestTemplateConfig.java
  src/test/java/com/sparta/nanglangeats/domain/payment/TossPaymentClientTest.java
Labels: feat

#118 [fix] OrderRepository 오류 수정
  src/main/java/com/sparta/nanglangeats/domain/order/repository/OrderRepository.java
Labels: fix

#119 [fix] 리뷰 엔드포인트 수정
  src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java
Labels: fix

#120 [feat] Swagger UI permitAll 설정
  src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
Labels: feat
